services:
  saleor-storefront:
    container_name: saleor-storefront
    build:
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SALEOR_API_URL: ${NEXT_PUBLIC_SALEOR_API_URL}
        NEXT_PUBLIC_STOREFRONT_URL: ${NEXT_PUBLIC_STOREFRONT_URL}
    restart: always
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - saleor_network
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_SALEOR_API_URL=${NEXT_PUBLIC_SALEOR_API_URL}
      - SALEOR_API_URL=http://host.docker.internal:8000/graphql/
      - AUTO_DETECT_API=false


  # Add more containers below (nginx, postgres, etc.)

networks:
  saleor_network:
    external: false
